version: '3.5'
services:
  database:
    container_name: "database"
    image: polypet-postgresdb
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=password


  customercare:
    image: 'teamj-archi-cloud-customer-care'
    container_name: teamj-archi-cloud-customer-care
    depends_on:
      - database
    environment:
      - POSTGRES_SERVER_URL=database
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/cloudpolypetcustomercaredb
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_DATASOURCE_USERNAME=anas
      - SPRING_DATASOURCE_PASSWORD=anas_69
      - MONITOR_SITE_URL=http://teamj-archi-site-monitoring:8004
      - INVENTORY_URL=http://teamj-archi-cloud-catalogue-manager:8081
      - BANK_URL=http://teamj-archi-cloud-bank:5002

  sitemonitor:
    image: 'teamj-archi-site-monitoring'
    container_name: teamj-archi-site-monitoring
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/cloudpolypetsitemonitoringdb
      - POSTGRES_SERVER_URL=database
      - SERVER_PORT=8004


  catalogue:
    image: 'teamj-archi-cloud-catalogue-manager'
    container_name: teamj-archi-cloud-catalogue-manager
    depends_on:
      - database
    environment:
      - MONITOR_SITE_URL=http://teamj-archi-site-monitoring:8004
      - POSTGRES_SERVER_URL=database
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/cloudpolypetbackenddb
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_DATASOURCE_USERNAME=anas
      - SPRING_DATASOURCE_PASSWORD=anas_69

  partner_ultima:
    image: 'teamj-archi-cloud-partner'
    container_name: "polypet-j-ultima"
    environment:
      - POSTGRES_SERVER_URL=database
      - PRODUCT={"name":"Medium Maxi Adult","category":"croquette","price":350}
      - COMPANY_NAME=Ultima
      - HOST=0.0.0.0
      - CURRENT_URL=http://polypet-j-ultima:5000
      - PARTNER_HOST=http://teamj-archi-cloud-catalogue-manager:8081
      - PORT=5000
    depends_on:
      - catalogue
    restart: always

  testrunner:
    image: 'polypet_j_test_consult_stats_issue_3'
    container_name: polypet_j_test_consult_stats_host_3
    depends_on:
      - catalogue
      - partner_ultima
    environment:
      - PARTNER_1_HOST=http://polypet-j-ultima:5000
      - BACKEND_HOST=http://teamj-archi-cloud-catalogue-manager:8081
      - MONITOR_SITE_URL=http://teamj-archi-site-monitoring:8004
      - MONITOR_HOST=http://teamj-archi-site-monitoring:8004
